spring.application.name=hibrido
server.port=8086

spring.datasource.primary.jdbc-url=jdbc:postgresql://localhost:5432/usco_hibrido_pg
spring.datasource.primary.username=postgres
spring.datasource.primary.password=1234
spring.datasource.primary.driver-class-name=org.postgresql.Driver

spring.datasource.secondary.jdbc-url=jdbc:mysql://localhost:3306/usco_hibrido_mysql?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.secondary.username=root
spring.datasource.secondary.password=
spring.datasource.secondary.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.open-in-view=false

app.jwt.secret=usco-hibrido-secret-key-2024-daniel-jimenez-32chars
app.jwt.expiration-ms=86400000

spring.thymeleaf.cache=false
spring.thymeleaf.encoding=UTF-8

spring.messages.basename=i18n/messages
spring.messages.encoding=UTF-8
spring.messages.fallback-to-system-locale=false